### PR TITLE
Adding Wiiflow compatibility for Wii64 based in FIX94's code in Wii64 fork

### PR DESCRIPTION
**Pull request by saulfabregwiivc**
Hi there @emukidid

I finished copying some code from @FIX94's fork of Wii64 (http://github.com/FIX94/Wii64) for be able to use Wii64 as a Wiiflow plugin, with posibility of using arguments for load automatically a ROM on startup.

In the meta.xml file, the arguments for use are:
`<arguments>`
`<arg>{device}:/{path_of_ROM}</arg>`
`<arg>{ROM_file}</arg>`
`</arguments>`

For example:
`<arguments>`
`<arg>sd:/apps/wii64_singlegame/rom</arg>`
`<arg>SuperMario64.z64</arg>`
`</arguments>`

Hope you can test this code and this will be merged to Wii64.

@saulfabregwiivc

### CODE REVIEW

**Comment by saulfabregwiivc** [comment]
Any interest for add this feature i'm trying to integrate to main Wii64?
Please, since this will be utile for WiiFlow, but also for people (like me) that like to have individual game launchers of Wii64 which also work with the Wii U GamePad.

**Comment by emukidid** [comment]
Yes there's interest, I just haven't had time to review.

**Comment by TriVoxel** [comment]
> Yes there's interest, I just haven't had time to review.

Hey are you able to merge this? Sounds cool. N64 emulation needs some more love on Wii U :(

**Comment by saulfabregwiivc** [comment]
Yep, any chance for add my WiiFlow plugin code based in @FIX94's code to main Wii64?

This will be useful for WiiFlow, and other game launchers including making custom simple game loaders, specially since Wii64 is the only N64 emulator for Wii which has Rice GFX for that problematic games that wouldn't run in glN64 GFX.

I'd like to see Wii64 (in all its versions) with arguments support for autolaunch ROMs, which will make it to be usable on WiiFlow as a plugin.

Thanks! @saulfabregwiivc

**Comment by saulfabregwiivc** [comment]
Pull request closed because of missing commits, i've opened a new one with all the required code ;)
https://github.com/emukidid/Wii64/pull/83

**Pull request closed without merging**
